// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plugin.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	plugin.proto

It has these top-level messages:
	Job
	Argument
	ManualInteraction
	JobResult
	Empty
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

// Job represents a single job
type Job struct {
	UniqueId    uint32             `protobuf:"varint,1,opt,name=unique_id,json=uniqueId" json:"unique_id,omitempty"`
	Title       string             `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Description string             `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Dependson   []uint32           `protobuf:"varint,4,rep,packed,name=dependson" json:"dependson,omitempty"`
	Args        []*Argument        `protobuf:"bytes,5,rep,name=args" json:"args,omitempty"`
	Interaction *ManualInteraction `protobuf:"bytes,6,opt,name=interaction" json:"interaction,omitempty"`
}

func (m *Job) Reset()                    { *m = Job{} }
func (m *Job) String() string            { return proto1.CompactTextString(m) }
func (*Job) ProtoMessage()               {}
func (*Job) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Job) GetUniqueId() uint32 {
	if m != nil {
		return m.UniqueId
	}
	return 0
}

func (m *Job) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Job) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Job) GetDependson() []uint32 {
	if m != nil {
		return m.Dependson
	}
	return nil
}

func (m *Job) GetArgs() []*Argument {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *Job) GetInteraction() *ManualInteraction {
	if m != nil {
		return m.Interaction
	}
	return nil
}

// Argument represents an argument passed from a pipeline
// to gaia and/or from gaia to the pipeline.
type Argument struct {
	Description string `protobuf:"bytes,1,opt,name=description" json:"description,omitempty"`
	Type        string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Value       string `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
}

func (m *Argument) Reset()                    { *m = Argument{} }
func (m *Argument) String() string            { return proto1.CompactTextString(m) }
func (*Argument) ProtoMessage()               {}
func (*Argument) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Argument) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Argument) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Argument) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// ManualInteraction represents a manual human interaction
type ManualInteraction struct {
	Description string `protobuf:"bytes,1,opt,name=description" json:"description,omitempty"`
	Type        string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Value       string `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
}

func (m *ManualInteraction) Reset()                    { *m = ManualInteraction{} }
func (m *ManualInteraction) String() string            { return proto1.CompactTextString(m) }
func (*ManualInteraction) ProtoMessage()               {}
func (*ManualInteraction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ManualInteraction) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ManualInteraction) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ManualInteraction) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// JobResult represents the result of an executed job
type JobResult struct {
	UniqueId     uint32 `protobuf:"varint,1,opt,name=unique_id,json=uniqueId" json:"unique_id,omitempty"`
	Failed       bool   `protobuf:"varint,2,opt,name=failed" json:"failed,omitempty"`
	ExitPipeline bool   `protobuf:"varint,3,opt,name=exit_pipeline,json=exitPipeline" json:"exit_pipeline,omitempty"`
	Message      string `protobuf:"bytes,4,opt,name=message" json:"message,omitempty"`
}

func (m *JobResult) Reset()                    { *m = JobResult{} }
func (m *JobResult) String() string            { return proto1.CompactTextString(m) }
func (*JobResult) ProtoMessage()               {}
func (*JobResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *JobResult) GetUniqueId() uint32 {
	if m != nil {
		return m.UniqueId
	}
	return 0
}

func (m *JobResult) GetFailed() bool {
	if m != nil {
		return m.Failed
	}
	return false
}

func (m *JobResult) GetExitPipeline() bool {
	if m != nil {
		return m.ExitPipeline
	}
	return false
}

func (m *JobResult) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// Empty message
type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto1.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func init() {
	proto1.RegisterType((*Job)(nil), "proto.Job")
	proto1.RegisterType((*Argument)(nil), "proto.Argument")
	proto1.RegisterType((*ManualInteraction)(nil), "proto.ManualInteraction")
	proto1.RegisterType((*JobResult)(nil), "proto.JobResult")
	proto1.RegisterType((*Empty)(nil), "proto.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Plugin service

type PluginClient interface {
	// GetJobs returns a stream of Job objects.
	// Used to expose jobs to gaia.
	GetJobs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Plugin_GetJobsClient, error)
	// ExecuteJob signals the plugin to execute the given job.
	// Used to execute one job from a pipeline.
	ExecuteJob(ctx context.Context, in *Job, opts ...grpc.CallOption) (*JobResult, error)
}

type pluginClient struct {
	cc *grpc.ClientConn
}

func NewPluginClient(cc *grpc.ClientConn) PluginClient {
	return &pluginClient{cc}
}

func (c *pluginClient) GetJobs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Plugin_GetJobsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Plugin_serviceDesc.Streams[0], c.cc, "/proto.Plugin/GetJobs", opts...)
	if err != nil {
		return nil, err
	}
	x := &pluginGetJobsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Plugin_GetJobsClient interface {
	Recv() (*Job, error)
	grpc.ClientStream
}

type pluginGetJobsClient struct {
	grpc.ClientStream
}

func (x *pluginGetJobsClient) Recv() (*Job, error) {
	m := new(Job)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pluginClient) ExecuteJob(ctx context.Context, in *Job, opts ...grpc.CallOption) (*JobResult, error) {
	out := new(JobResult)
	err := grpc.Invoke(ctx, "/proto.Plugin/ExecuteJob", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Plugin service

type PluginServer interface {
	// GetJobs returns a stream of Job objects.
	// Used to expose jobs to gaia.
	GetJobs(*Empty, Plugin_GetJobsServer) error
	// ExecuteJob signals the plugin to execute the given job.
	// Used to execute one job from a pipeline.
	ExecuteJob(context.Context, *Job) (*JobResult, error)
}

func RegisterPluginServer(s *grpc.Server, srv PluginServer) {
	s.RegisterService(&_Plugin_serviceDesc, srv)
}

func _Plugin_GetJobs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PluginServer).GetJobs(m, &pluginGetJobsServer{stream})
}

type Plugin_GetJobsServer interface {
	Send(*Job) error
	grpc.ServerStream
}

type pluginGetJobsServer struct {
	grpc.ServerStream
}

func (x *pluginGetJobsServer) Send(m *Job) error {
	return x.ServerStream.SendMsg(m)
}

func _Plugin_ExecuteJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Job)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).ExecuteJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Plugin/ExecuteJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).ExecuteJob(ctx, req.(*Job))
	}
	return interceptor(ctx, in, info, handler)
}

var _Plugin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Plugin",
	HandlerType: (*PluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteJob",
			Handler:    _Plugin_ExecuteJob_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetJobs",
			Handler:       _Plugin_GetJobs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "plugin.proto",
}

func init() { proto1.RegisterFile("plugin.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 381 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0x41, 0x8b, 0xd4, 0x30,
	0x18, 0x25, 0xce, 0x4c, 0xa7, 0xfd, 0x3a, 0x83, 0x1a, 0x54, 0xc2, 0xea, 0xa1, 0x74, 0x59, 0x28,
	0x1e, 0x06, 0x19, 0x6f, 0xde, 0x5c, 0x59, 0x96, 0x2d, 0x08, 0x25, 0x07, 0x2f, 0x1e, 0x86, 0x74,
	0xfa, 0x59, 0x02, 0x9d, 0x24, 0xb6, 0x89, 0xec, 0x9e, 0xfc, 0x9d, 0xfe, 0x1b, 0x99, 0xa4, 0x65,
	0x06, 0x17, 0x3c, 0xed, 0xa9, 0x79, 0xef, 0x7b, 0x7c, 0xef, 0xbd, 0x26, 0xb0, 0x32, 0x9d, 0x6b,
	0xa5, 0xda, 0x98, 0x5e, 0x5b, 0x4d, 0x17, 0xfe, 0x93, 0xff, 0x21, 0x30, 0x2b, 0x75, 0x4d, 0xdf,
	0x42, 0xe2, 0x94, 0xfc, 0xe9, 0x70, 0x27, 0x1b, 0x46, 0x32, 0x52, 0xac, 0x79, 0x1c, 0x88, 0xbb,
	0x86, 0xbe, 0x82, 0x85, 0x95, 0xb6, 0x43, 0xf6, 0x2c, 0x23, 0x45, 0xc2, 0x03, 0xa0, 0x19, 0xa4,
	0x0d, 0x0e, 0xfb, 0x5e, 0x1a, 0x2b, 0xb5, 0x62, 0x33, 0x3f, 0x3b, 0xa7, 0xe8, 0x3b, 0x48, 0x1a,
	0x34, 0xa8, 0x9a, 0x41, 0x2b, 0x36, 0xcf, 0x66, 0xc5, 0x9a, 0x9f, 0x08, 0x7a, 0x09, 0x73, 0xd1,
	0xb7, 0x03, 0x5b, 0x64, 0xb3, 0x22, 0xdd, 0x3e, 0x0f, 0xb9, 0x36, 0x9f, 0xfb, 0xd6, 0x1d, 0x50,
	0x59, 0xee, 0x87, 0xf4, 0x13, 0xa4, 0x52, 0x59, 0xec, 0xc5, 0xde, 0x9b, 0x44, 0x19, 0x29, 0xd2,
	0x2d, 0x1b, 0xb5, 0x5f, 0x85, 0x72, 0xa2, 0xbb, 0x3b, 0xcd, 0xf9, 0xb9, 0x38, 0xff, 0x06, 0xf1,
	0xb4, 0xed, 0xdf, 0xb0, 0xe4, 0x71, 0x58, 0x0a, 0x73, 0xfb, 0x60, 0xa6, 0x8e, 0xfe, 0x7c, 0x2c,
	0xfe, 0x4b, 0x74, 0x0e, 0xc7, 0x72, 0x01, 0xe4, 0x3b, 0x78, 0xf9, 0xc8, 0xf9, 0x49, 0x0d, 0x7e,
	0x43, 0x52, 0xea, 0x9a, 0xe3, 0xe0, 0x3a, 0xfb, 0xff, 0x9b, 0x79, 0x03, 0xd1, 0x0f, 0x21, 0x3b,
	0x6c, 0xfc, 0xd6, 0x98, 0x8f, 0x88, 0x5e, 0xc2, 0x1a, 0xef, 0xa5, 0xdd, 0x19, 0x69, 0xb0, 0x93,
	0x2a, 0xec, 0x8f, 0xf9, 0xea, 0x48, 0x56, 0x23, 0x47, 0x19, 0x2c, 0x0f, 0x38, 0x0c, 0xa2, 0x45,
	0x36, 0xf7, 0xf6, 0x13, 0xcc, 0x97, 0xb0, 0xb8, 0x39, 0x18, 0xfb, 0xb0, 0xfd, 0x0e, 0x51, 0xe5,
	0x5f, 0x0d, 0xbd, 0x82, 0xe5, 0x2d, 0xda, 0x52, 0xd7, 0x03, 0x5d, 0x8d, 0xbf, 0xdf, 0x4b, 0x2e,
	0x60, 0x44, 0xa5, 0xae, 0x3f, 0x10, 0xfa, 0x1e, 0xe0, 0xe6, 0x1e, 0xf7, 0xce, 0xe2, 0xf1, 0x55,
	0x9d, 0xcd, 0x2e, 0x5e, 0x9c, 0xce, 0xa1, 0xd9, 0xf5, 0x15, 0xbc, 0x96, 0x7a, 0xd3, 0x0a, 0x29,
	0xa6, 0x98, 0x41, 0x72, 0x0d, 0xb7, 0xbc, 0xfa, 0x12, 0x7c, 0x2b, 0x52, 0x47, 0x9e, 0xfc, 0xf8,
	0x37, 0x00, 0x00, 0xff, 0xff, 0xeb, 0xe6, 0x3c, 0x69, 0xc0, 0x02, 0x00, 0x00,
}
